Подключение существующей ИБ как рабочей
oscript-library/packman pull request #33
Opened 2019-01-09 12:18 UTC by ZhdanovR

## Проблема

В текущей реализации нельзя использовать существующую ИБ в качестве сборочной

## Что сделано

- Добавлена новая команда  set-database

## Как работает?

В сборочном каталоге командой set-database создается служебный файл с параметрами авторизации к ИБ. При работе других команд проверяется наличие этого файла. Если о существует, то данные подключения берутся с него, в противном случае используется старый механизм

2019-01-09 12:20 UTC, ZhdanovR commented
По результатом последних изменений тесты проходят
![default](https://user-images.githubusercontent.com/26283990/50899095-4ed94a80-143b-11e9-8879-ec58e28b5b38.png)

2019-01-09 12:36 UTC, EvilBeaver requested changes

2019-01-09 12:36 UTC, EvilBeaver commented on README.md
> +* Использовать существующую ИБ в качестве рабочей
Не нужна строчка. Наличие "рабочей" ИБ это технический момент, это не часть "возможностей" программы.

2019-01-09 12:36 UTC, EvilBeaver commented on README.md
> +При использовании существующей ИБ в качестве рабочей (например, формирование поставки непосредственно с тестового контура), будьте внимательны при использовании команд выгрузки из хранилища, а так же
Каким образом команда выгрузки из хранилища необратима по отношению к базе?

2019-01-09 12:36 UTC, EvilBeaver commented on src/Модули/ОкружениеСборки.os
> +    Лог.Информация("Ищу файл настройки подключения к ИБ");
Не нужно это сообщение

2019-01-09 12:36 UTC, EvilBeaver commented on src/Модули/ОкружениеСборки.os
> +        Лог.Информация("Файл настройки подключения не найден");
Лучше понизить уровень до Отладка

2019-01-10 10:05 UTC, EvilBeaver requested changes

2019-01-10 10:05 UTC, EvilBeaver commented on README.md
> +При использовании существующей ИБ в качестве рабочей (например, формирование поставки непосредственно с тестового контура), будьте внимательны при использовании команд выгрузки из хранилища, а так же
Я так и не понял. Что опасного с выгрузкой CF из хранилища? Может речь про **обновление базы из хранилища**?

2019-01-10 12:55 UTC, merged